name: Lambda Pre Step
description: Lambdaå‰å‡¦ç†

inputs:
  lambda_name:
    required: true
    description: 'å¯¾è±¡Lambdaå'

outputs:
  pre_message:
    description: "å‰å‡¦ç†ã§ç”Ÿæˆã—ãŸãƒ¡ãƒƒã‚»ãƒ¼ã‚¸"
    value: ${{ steps.set_message.outputs.pre_message }}

runs:
  using: "composite"
  steps:
    - id: set_message
      run: |
        echo "ðŸš§ Lambda name is ${{ inputs.lambda_name }}"
        echo "pre_message=Hello from Pre for ${{ inputs.lambda_name }}" >> $GITHUB_OUTPUT
      shell: bash
