name: Lambda Pre Step
description: Lambda前処理

inputs:
  lambda_name:
    required: true
    description: '対象Lambda名'

outputs:
  pre_output:
    description: "前処理で生成したメッセージ"

runs:
  using: "composite"
  steps:
    - run: |
        echo "🚧 Lambda name is ${{ inputs.lambda_name }}"
        echo "pre_output=Hello from Pre for ${{ inputs.lambda_name }}" >> $GITHUB_OUTPUT
      shell: bash
