name: Lambda Main Step
description: Lambdaメイン処理

inputs:
  lambda_name:
    required: true
  pre_output:
    required: false

outputs:
  zip_path:
    description: "生成されたZIPパス"
    value: function.zip

runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p build
        echo "dummy content" > build/lambda_function.py
        cd build
        zip -r ../function.zip .
      shell: bash

    - run: |
        echo "📝 受け取った pre_output: $PRE_OUTPUT"
      shell: bash
      env:
        PRE_OUTPUT: ${{ inputs.pre_output }}
